### ISSUE TITLE
Memory management during file attachment

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#3]
When attaching a file dataset uses a lot of memory (2-3x file size)

**Comment by rsdoiel** [comment]
Right now we build the attached tar ball in memory which is best for most of our use cases.  I need to decided what "large file" means and when that boundary is crossed build the tar ball using temp disc space. This will make the process slow but allow it to fix in memory. This adds complexity to how we currently interact with S3 and Google Cloud Storage as we'll still need local disc space to build the tarball.

Another approach would be to dispense with the tarball and just store the raw file. To prevent directory nesting attachments would be attached based on the path.Base() of their name rather than their full path.  If someone had files with duplicate names they'd need to zip/tar them first and attach the compressed version of the file tree.

**Comment by rsdoiel** [comment]
Moving to a pairtree directory layout will give us an opportunity to drop putting things in tar balls. This will resolved the memory consumption issues in managing the tar file.
